# Generated by Django 4.0.2 on 2022-02-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField()),
            ],
        ),
    ]
